### ISSUE TITLE
When i activate tuner Laptop it activates but doesnt show anymore

### ISSUE THREAD

**Issue by TDRUSH** [qbcore-framework/qb-tunerchip#48] opened 2022-09-22 05:40 UTC
When i activate tuner Laptop it activates but doesnt show anymore.
This happens at random with different cars.
Dont get error messages on server or client side.
in the beginning it opens a couple of times like it should no problems at all then at random itactivates cause you see the cursor popup but screen doesnt show. after that i cant use it again not even after server restart.
After it happenned i dove into the logs But no error messages pop up the tuning screen just wont show.

**To Reproduce**
its completly at random so cant specify a way to reproduce

**Expected behavior**
To see the tuner screen popup 

**Screenshots**
![image](https://user-images.githubusercontent.com/112986403/191666348-402b8391-c254-4194-bc36-a1c0ef067c73.png)
first one is when opening the tuner chip

![image](https://user-images.githubusercontent.com/112986403/191666487-0e337e93-c599-4015-801d-596b5bd8ee62.png)
2nd one is from when the tuner chip is suppossed to show inscreen  but you only see Mouse cursor.

at that poiint i can only press esc to continue with the game/to close the tuner part

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]  - yesterday
 - Are you using custom resource? which ones?  - QB-target 
 - Have you renamed `qb-` to something custom?  - no

**Additional context**

**Comment by CaptainMooseStudios** [comment] 2022-09-24 07:47
I have the same issue

**Comment by MrRustyKMaynard** [comment] 2022-10-03 15:47
Also having this issue, Anyone heard of any possible reason/fix?

**Comment by Killerhunter100** [comment] 2023-01-09 15:48
i think the problem is now fixed just try downloading the latest version
i tested the bug and i found it fixed
tell me if still have the problem to help you with it

**Closed** 2023-01-18 17:33 UTC
Labels: bug
